baseURL = "https://hugo-blog-6le.pages.dev/"
languageCode = "ja-JP"
title = "Typo職人の文化資産庫"
theme = "hugo-PaperMod"
googleAnalytics = "G-RLG3LK7VRJ"
[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    name = "Parts"
    url = "/parts/"
    weight = 20
  [[menu.main]]
    name = "Terms"
    url = "/terms/"
    weight = 30
[params]
  defaultTheme = "auto"
  mainSections = ["posts","parts"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
